server:
  port: 8001

#mybatis的配置
mybatis:
  type-aliases-package: com.ren.cloud.info
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: prvider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/rellys?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#management:
#  context-path: /admin

#logging:
#  level:
#    com.netflix.discovery: 'OFF'
#     org.springframework.cloud: 'DEBUG'

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health